alter table public.admin_settings add column if not exists email_auto_reply_enabled boolean default false;
alter table public.admin_settings add column if not exists email_auto_reply_subject text default 'We got your message';
alter table public.admin_settings add column if not exists email_auto_reply_body text default E'Hi {{first_name}},\n\nThank you for messaging Streamz R Us.\n\nA member of the team will be with you shortly.\n\nDue to high demand, please allow up to 24 hours for a reply, although it is usually much quicker.\n\nThanks,\nStreamz R Us';

create table if not exists public.email_auto_reply_log (
  id bigint generated by default as identity primary key,
  mailbox_user text not null,
  message_uid bigint not null,
  recipient_email text not null,
  auto_reply_subject text,
  replied_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (mailbox_user, message_uid)
);

grant all on public.email_auto_reply_log to authenticated;
grant select on public.email_auto_reply_log to anon;

alter table public.email_auto_reply_log enable row level security;

drop policy if exists "Authenticated users can view auto reply log" on public.email_auto_reply_log;
create policy "Authenticated users can view auto reply log" on public.email_auto_reply_log
  for select to authenticated
  using (true);

drop policy if exists "Authenticated users can insert auto reply log" on public.email_auto_reply_log;
create policy "Authenticated users can insert auto reply log" on public.email_auto_reply_log
  for insert to authenticated
  with check (true);

update public.admin_settings
set
  email_auto_reply_enabled = coalesce(email_auto_reply_enabled, false),
  email_auto_reply_subject = coalesce(email_auto_reply_subject, 'We got your message'),
  email_auto_reply_body = coalesce(
    email_auto_reply_body,
    E'Hi {{first_name}},\n\nThank you for messaging Streamz R Us.\n\nA member of the team will be with you shortly.\n\nDue to high demand, please allow up to 24 hours for a reply, although it is usually much quicker.\n\nThanks,\nStreamz R Us'
  )
where id = 1;
